 steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/code-review-gitlab', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/code-review-gitlab']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'code-review-gitlab',
      '--image=gcr.io/$PROJECT_ID/code-review-gitlab',
      '--platform=managed',
      '--allow-unauthenticated',
      '--region=us-central1',
      '--set-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/app/key.json'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  
timeout: '600s'
