steps:
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        python app.py

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']

substitutions:
  _GOOGLE_APPLICATION_CREDENTIALS: 'agent-development-461516-c58cccfe9b84.json'

timeout: '600s'
